name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Cloud Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Get Buildozer Cache
      uses: actions/cache@v4
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v3
      with:
        command: buildozer android debug
        repository_root: .

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AlMandoub-APK
        path: bin/*.apk

